name: LBE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60832
title: LÄUFT-BEI-EUCH.DE - Homepages - Onlineshops - Facebook-Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
